---
plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.5
  NewCops: enable

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - rackfile
    - app/controllers/*.rb

Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*

Style/SymbolArray:
  Enabled: true
  Exclude:
    - db/migrations/**/*
    - rackfile

Naming/RescuedExceptionsVariableName:
  Enabled: true
  PreferredName: error