---
plugins:
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.5
  NewCops: enable

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - rackfile

Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*

Style/SymbolArray:
  Enabled: true
  Exclude:
    - db/migrations/**/*
    - rackfile