---
# Rename file to secrets.yml to get started for development or test

development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: your_session_secret_key
  REDISCLOUD_URL: redis://URL
  MSG_KEY: <`rake generate:msg_key`>

test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: your_session_secret_key
  MSG_KEY: <`rake generate:msg_key`>

production:
  API_URL: <provisioned API URL (ending with api/[version])>
  APP_URL: <provisioned app URL (root without ending slash)>
  SESSION_SECRET: your_session_secret_key
  MSG_KEY: <`rake generate:msg_key`>