---
# Rename file to secrets.yml to get started for development or test

development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: your_session_secret_key
  MSG_KEY: <`rake generate:msg_key`>
  REDISCLOUD_URL: redis://localhost:6379
  GOOGLE_CLIENT_ID: your_google_client_id
  GOOGLE_CLIENT_SECRET: your_google_client_secret
  GOOGLE_SCOPE: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
  GOOGLE_OAUTH_URL: https://accounts.google.com/o/oauth2/v2/auth
  GOOGLE_TOKEN_URL: https://oauth2.googleapis.com/token
  GOOGLE_REDIRECT_URI: http://localhost:9292/auth/login




test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: your_session_secret_key
  MSG_KEY: <`rake generate:msg_key`>
  REDISCLOUD_URL: redis://localhost:6379
  GOOGLE_CLIENT_ID: your_google_client_id
  GOOGLE_CLIENT_SECRET: your_google_client_secret
  GOOGLE_SCOPE: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
  GOOGLE_OAUTH_URL: https://accounts.google.com/o/oauth2/v2/auth
  GOOGLE_TOKEN_URL: https://oauth2.googleapis.com/token
  GOOGLE_REDIRECT_URI: http://localhost:9292/auth/login


production:
  API_URL: <provisioned API URL (ending with api/[version])>
  APP_URL: <provisioned app URL (root without ending slash)>
  SESSION_SECRET: your_session_secret_key
  MSG_KEY: <`rake generate:msg_key`>
  REDISCLOUD_URL: redis://REDIS_CLOUD_URL
  GOOGLE_CLIENT_ID: your_google_client_id
  GOOGLE_CLIENT_SECRET: your_google_client_secret
  GOOGLE_SCOPE: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
  GOOGLE_OAUTH_URL: https://accounts.google.com/o/oauth2/v2/auth
  GOOGLE_TOKEN_URL: https://oauth2.googleapis.com/token
  GOOGLE_REDIRECT_URI: http://localhost:9292/auth/login
