---
# Rename file to secrets.yml to get started for development or test

development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: your_session_secret_key
  MSG_KEY: <`rake generate:msg_key`>
  REDISCLOUD_URL: redis://localhost:6379
  GH_OAUTH_URL: https://github.com/login/oauth/authorize
  GH_TOKEN_URL: https://github.com/login/oauth/access_token
  GH_SCOPE: user:email
  GH_CLIENT_ID: your_github_client_id
  GH_CLIENT_SECRET: your_google_client_secret



test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: your_session_secret_key
  MSG_KEY: <`rake generate:msg_key`>
  REDISCLOUD_URL: redis://localhost:6379
  GH_OAUTH_URL: https://github.com/login/oauth/authorize
  GH_TOKEN_URL: https://github.com/login/oauth/access_token
  GH_SCOPE: user:email
  GH_CLIENT_ID: your_github_client_id
  GH_CLIENT_SECRET: your_google_client_secret




production:
  API_URL: <provisioned API URL (ending with api/[version])>
  APP_URL: <provisioned app URL (root without ending slash)>
  SESSION_SECRET: your_session_secret_key
  MSG_KEY: <`rake generate:msg_key`>
  REDISCLOUD_URL: redis://REDIS_CLOUD_URL
  GH_OAUTH_URL: https://github.com/login/oauth/authorize
  GH_TOKEN_URL: https://github.com/login/oauth/access_token
  GH_SCOPE: user:email
  GH_CLIENT_ID: your_github_client_id
  GH_CLIENT_SECRET: your_google_client_secret


